### ISSUE TITLE
Elusive target global "silent assassin" challenges are broken due to "$reset"

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/StateMachineParser#14]
`"ce8b2dbb-3730-468e-90c2-faba14c5ed6a"` and `"7b6082fa-76f4-456c-a4a2-c8b84f9d63db"` are broken because the `witnesses` and `targets` arrays are not correctly cleared on `$reset`.

**Comment by moonysolari** [comment]
Yeah, so these challenges will have their contexts saved to the user profile because they have `"RuntimeType": "Hit"`. Their contexts will include the `Witnesses` array. If you start an et session and gain some witnesses, then start another et session, and print out the contexts of these challenges after an event has been handled you will see that the `Witnesses` array is not an empty array. I guess that `reset` is resetting them to whatever was read from the user profiles instead of their real original values.

**Comment by AnthonyFuller** [comment]
Does the _definition_ get changed though. That's where the original context comes from.

**Comment by moonysolari** [comment]
It seems that the definition DID get changed. very curious. Then it's not a bug of `$reset`. I suspect that the user context was loaded and stored to `challenge.Definition.Context`.
